### PR TITLE
#586:  Added extra parameters to allow the SSO of alternative pull fr…

### PR DESCRIPTION
**Pull request by cbeach47**
…om LMS flows to work

Adding this to 2018.2 since it's low risk / minor change but will fix a bug in the Canvas flows.

@abidingotter - do you have a scenario to test the following?  The 3 SSO flows work now.
- custom_course_id is added to the courseCodes
- custom_course_code is added to the courseCodes
- lis_course_offering_sourcedid is added to the courseCodes

#586

### CODE REVIEW

**Comment by abidingotter** [comment]
I think lis_course_offering_sourcedid would either be passed in automatically, or not at all.  
The custom ones you can add to the LTI config (you would need to copy and paste the XML and then edit it)
`<lticm:property name="custom_course_id">$Canvas.course.id</lticm:property>`

**Comment by edalex-ian** [comment]
Will hold until post 2018.2 release as we're in code freeze.

**Comment by edalex-ian** [comment]
Link PR to #586

**Comment by edalex-ian** [comment]
Heya @cbeach47 

Happy for you to merge this in and backport to the 2018.2 branch.

Are you able to test as well?

**Comment by cbeach47** [comment]
@edalex-ian - I'll go ahead and merge / backport it.

@abidingotter - I was curious if you had a known test scenario that would test how the those 3 properties are used - makes sense that we can add in the custom parameters after the fact if needed.  Since this PR doesn't affect those 3, I don't view it as a blocker to merging.

> I think lis_course_offering_sourcedid would either be passed in automatically, or not at all.
> The custom ones you can add to the LTI config (you would need to copy and paste the XML and then edit it)
> `<lticm:property name="custom_course_id">$Canvas.course.id</lticm:property>`

**Comment by ChristianMurphy** [comment]
@cbeach47 is this this ready to merge and backport?

**Comment by ChristianMurphy** [comment]
@cbeach47 Something seems off with the commit history, 161 commits when 1-3 are expected.

**Comment by cbeach47** [comment]
I rebased off of develop and something must have went wonky.  I'll close this and reopen.

**Pull request closed without merging**
