### PR TITLE
Fix hook installer on Windows

### PR DESCRIPTION
**Pull request by abidingotter**
#1123

### CODE REVIEW

**Comment by edalex-ian** [comment]
It looks okay, guess first someone on linux should try a fresh clone and `npm install` and make sure it works.

**Comment by mrblippy** [comment]
I got the following error after running npm install on a fresh clone on windows (using MINGW64)
BITSADMIN version 3.0
BITS administration utility.
(C) Copyright Microsoft Corp.

Unable to add file - 0x8007010b
Error: Unable to access jarfile E:\edalex\repos\openEQUELLA2\target\coursier
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn coursier bootstrap com.geirsson:scalafmt-cli_2.12:1.5.1 -f -o node_modules\.bin\scalafmt && .\coursier bootstrap com.google.googlejavaformat:google-java-format:1.7 -f -o node_modules\.bin\google-java-format ENOENT
    at notFoundError (E:\edalex\repos\openEQUELLA2\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (E:\edalex\repos\openEQUELLA2\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (E:\edalex\repos\openEQUELLA2\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openequella@ install: `cross-env-shell "./coursier bootstrap com.geirsson:scalafmt-cli_2.12:1.5.1 -f -o node_modules/.bin/scalafmt && ./coursier bootstrap com.google.googlejavaformat:google-java-format:1.7 -f -o node_modules/.bin/google-java-format"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openequella@ install script.

**Comment by edalex-ian** [comment]
Ahhh, well after seeing @mrblippy 's issues above we had a closer look. It seems all we really needed (other than added cross-env-shell) was to update couriser.bat and coursier with the latest versions. And better yet, once doing that there is now downloading on demand.

Now just to make sure that works fine in Linux land.

**Comment by mrblippy** [comment]
Verified both npm install and the pre-commit hooks both work in windows on a fresh clone of the repo. We can merge once the checks have passed

**Pull request merged**
