### PR TITLE
New UI autotest fixes

### PR DESCRIPTION
**Pull request by doolse**
This is the work done to get the autotests working on the new ui.

In order to actually run with the new UI tests on the build needs to run with `tests.newui = true` which you should be able to override at the build level, by passing in -Dtests.newui=true to the sbt jvm somehow

### CODE REVIEW

**Comment by edalex-ian** [comment]
As can be seen, a concerted effort has now commenced to see this through to completion. Watch this space.

**Comment by doolse** [comment]
@PenghaiZhang @edalex-ian Before you continue on this branch, I spent a good chunk of last week working on this on my fork : https://github.com/doolse/Equella/commits/bugfix/autotest-newui 
Some of which are fixed bugs which I intend to make issues/pull requests for. The latest list of failures is commited in the branch: 
https://github.com/doolse/Equella/commit/9f58194a56be16d8a4c7224ed8e0754ba0001c08
Only 13 classes left, most of which are bugs in the product.
Perhaps we should set up a call to discuss?

**Comment by edalex-ian** [comment]
Good stuff @doolse 

> Perhaps we should set up a call to discuss?

Sounds like a good idea. I wont join in, but sounds great if you, @SammyIsConfused and @PenghaiZhang have a chat and get on the same page to avoid overlap.

**Comment by doolse** [comment]
@SammyIsConfused @PenghaiZhang I'm free at 10:30 (or some other time if you like), send through a hangout link to doolse@gmail.com

**Comment by edalex-ian** [comment]
Hold on, that was auto closed due to the merge and delete of the release branch. Retargetting.

**Comment by edalex-ian** [comment]
Or not... I suggest a new PR is needed, looks like you can't retarget after target branch gone. :'(

**Pull request closed without merging**
