### PR TITLE
Logon filter fix for new UI - CAS

### PR DESCRIPTION
**Pull request by doolse**
#1116

### CODE REVIEW

**Comment by edalex-ian** [comment]
Heya @doolse 

Did you by chance run any of the New UI autotest stuff against this? (Would've been a bit of messing around, but would just help us have more confidence of whether there's any regressions.)

**Comment by doolse** [comment]
Yeah I will merge the new UI autotest branch in and see how it goes. (The results will take some interpreting as there was still 50 or so failures)

**Comment by doolse** [comment]
I have run the autotests on this and appeared to be ok - the failures didn't appear to be related at all.

**Comment by edalex-ian** [comment]
Heya @doolse 

Could you please resubmit this PR targetting `develop` and we'll get it merged in?

It looks like it was ready to go, just not merged. So hopefully we can do it straight away.

Cheers,
Ian.

**Pull request closed without merging**
